---
version: '3.8'

services:
  demo-mkdocs:
    container_name: demo-mkdocs
    image: demo-mkdocs
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
