---
version: '3.8'

services:
  mkdocs:
    container_name: nx-mkdocs
    image: nx-mkdocs
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
